### ISSUE TITLE
Broken release

### ISSUE THREAD

**Issue by web-mech** [Mechazawa/vue2-teleport#5]
The latest work done since last year breaks the ability to close modals. It is a breaking change with just a minor bump in the semver. If a breaking change is indeed intended, we should bump major, e.g. 2.xx. Does not work on any of my nuxt 2 apps.

**Comment by web-mech** [comment]
This PR looks like the likely cause https://github.com/Mechazawa/vue2-teleport/pull/2

**Comment by jackiotyu** [comment]
Sorry. Can you try the fix code or the fixed package? 
#7 
https://www.npmjs.com/package/jackiotyu-vue2-teleport-fix
